# Generated by Django 4.2 on 2023-05-17 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_country_place_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_addcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='addcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addcomment',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
    ]
