# Generated by Django 4.2 on 2023-05-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_addcomment_created_on_addcomment_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
