# Generated by Django 4.2 on 2023-05-20 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_addcomment_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='addcomment',
            name='website',
        ),
    ]
