# Generated by Django 4.2 on 2023-06-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_addcomment_email_remove_addcomment_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_post', to='blog.post', verbose_name='post'),
        ),
    ]
