# Generated by Django 4.2 on 2023-04-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'PropertyImages', 'verbose_name_plural': 'PropertyImages'},
        ),
    ]
