# Generated by Django 4.2 on 2023-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
