# Generated by Django 4.2 on 2023-05-11 06:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertybook_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
